# Generated by Django 5.2 on 2025-04-11 04:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GithubLake",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name="GithubUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=63)),
            ],
        ),
        migrations.CreateModel(
            name="GithubRepo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=255)),
                ("description", models.TextField(null=True)),
                ("html_url", models.URLField(max_length=511)),
                ("readme", models.TextField(null=True)),
                (
                    "github_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bum_poc.githubuser",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OSMPlace",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("entry", models.CharField(max_length=511)),
                ("data", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["entry"], name="bum_poc_osm_entry_dc9a05_idx"
                    )
                ],
            },
        ),
    ]
